import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: process.env.CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const ctx = await b.newContext({ viewport: { width: +(process.env.W || 852), height: +(process.env.H || 393) }, isMobile: true, hasTouch: true });
const p = await ctx.newPage();
const errs = [];
p.on('pageerror', e => { errs.push(e.message); console.log('[pageerror]', e.message, e.stack?.slice(0, 600)); });
p.on('console', m => { if (m.type() === 'error' && !m.text().includes('Failed to load resource')) console.log('[console]', m.text().slice(0, 300)); });
await p.goto('http://localhost:8000/index.html');
await p.evaluate(() => localStorage.removeItem('zoomies-career-v1'));
await p.reload();
await p.waitForFunction(() => window.zoomies && window.zoomies.race, null, { timeout: 30000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: 'car/0-title.png' });
await p.tap('[data-go="career"]');
await p.waitForTimeout(1500);
await p.screenshot({ path: 'car/1-story.png' });
console.log('screen', await p.evaluate(() => window.zoomies.ui.current));
for (let i = 0; i < 4; i++) { await p.tap('#scr-story .story-box'); await p.waitForTimeout(300); }
await p.waitForTimeout(1500);
console.log('screen after story', await p.evaluate(() => window.zoomies.ui.current));
await p.screenshot({ path: 'car/2-hub.png' });
await p.tap('#ev-list [data-ev="c1-4"]');
await p.waitForTimeout(1200);
await p.screenshot({ path: 'car/3-hub-sel.png' });
// garage
await p.evaluate(() => { window.zoomies.career.coins = 3000; });
await p.tap('#scr-career [data-go="garage"]');
await p.waitForTimeout(1500);
await p.screenshot({ path: 'car/4-garage-karts.png' });
await p.tap('#garage-list [data-pick="classic"]');
await p.waitForTimeout(800);
await p.screenshot({ path: 'car/5-garage-classic.png' });
await p.tap('#gar-act');
await p.waitForTimeout(500);
await p.tap('#garage-tabs [data-tab="upgrades"]');
await p.waitForTimeout(500);
await p.tap('#garage-list [data-pick="engine"]');
await p.tap('#garage-list [data-pick="engine"]');
await p.tap('#garage-list [data-pick="turbo"]');
await p.waitForTimeout(600);
await p.screenshot({ path: 'car/6-garage-upg.png' });
await p.tap('#garage-tabs [data-tab="racers"]');
await p.waitForTimeout(600);
await p.screenshot({ path: 'car/7-garage-racers.png' });
await p.tap('#garage-tabs [data-tab="paint"]');
await p.tap('#garage-list [data-pick="grape"]');
await p.waitForTimeout(600);
await p.tap('#gar-act');
await p.waitForTimeout(600);
await p.screenshot({ path: 'car/8-garage-paint.png' });
console.log('career', await p.evaluate(() => JSON.stringify(window.zoomies.career)));
await p.tap('#scr-garage [data-go="back"]');
await p.waitForTimeout(1200);
console.log('screen', await p.evaluate(() => window.zoomies.ui.current));
// run event c1-1 with the AI driving
await p.tap('#ev-list [data-ev="c1-1"]');
await p.tap('#car-go');
await p.waitForTimeout(2500);
await p.screenshot({ path: 'car/9-race.png' });
const r = await p.evaluate(async () => {
  const app = window.zoomies; const race = app.race;
  const { AIDriver } = await import('./src/ai.js');
  race.player.ai = new AIDriver(race.player, race, 0.95, race.diff);
  app.paused = true;
  let n = 0; while (!race.results && n++ < 60 * 300) race.update(1 / 60);
  app.paused = false;
  return { mode: race.mode, n, body: race.player.bodyDef.id, paint: race.player.paint, stats: race.player.stats, others: race.karts.map((k) => k.ch.id + ':' + k.bodyDef.id) };
});
console.log(JSON.stringify(r));
await p.waitForTimeout(1500);
if (await p.isVisible('#podium-ui')) { await p.screenshot({ path: 'car/09-podium.png' }); await p.tap('#podium-ui'); await p.waitForTimeout(700); }
await p.screenshot({ path: 'car/10-results.png' });
console.log('coins', await p.evaluate(() => window.zoomies.career.coins), 'stars', await p.evaluate(() => JSON.stringify(window.zoomies.career.stars)));
await p.tap('#res-buttons [data-go="career"]');
await p.waitForTimeout(1500);
await p.screenshot({ path: 'car/11-hub-after.png' });
console.log('errors', errs.length);
await b.close();
